### PR TITLE
Proposing adding gmallen to the master

### PR DESCRIPTION
**Pull request by gmallen**
more text here

### CODE REVIEW

**Comment by crichID** [comment]
Let's only merge one file here. new-file.md will be confusing later on when everyone is using the same folder!

**Comment by gmallen** [comment]
@jaelle Can you add a comment?

**Comment by cmcfaul** [comment]
If you delete `new-file.md`, you should move that information into `gmallen`.

**Comment by mandy72** [comment]
Looks good! :+1:

**Comment by jaelle** [comment]
Looks good @gmallen :shipit:

**Pull request merged**
