### PR TITLE
[WIP] Blank file template for tomtranschool-what-the-pho

### PR DESCRIPTION
**Pull request by tomtranschool**
:warning: This is work in progress and not yet ready :warning:

This feature contains work for describing a good place to start happy hour

:beers:

### CODE REVIEW

**Comment by mattgrogan** [comment]
I'll toast to that... :bread:

**Comment by tomtranschool** [comment]
when do we start @mattgrogan

**Comment by mattgrogan** [comment]
When you've memorized all these git commands...

**Comment by tomtranschool** [comment]
They call me Rain man Tom. Done! @mattgrogan

**Pull request closed without merging**
