### PR TITLE
I added my favorite restaurant to my info

### PR DESCRIPTION
**Pull request by theyounggriff**
I just wanted to let people know that company burger is rad.

### CODE REVIEW

**Comment by theyounggriff** [comment]
@nickymast Could you look it over?

**Comment by crichID** [comment]
@theyounggriff sounds yummy :+1:

**Comment by cynthiatayloronline** [comment]
Where is that?

**Comment by amarquette** [comment]
i like this change

**Comment by theyounggriff** [comment]
@cynthiatayloronline  Freret Street

**Pull request merged**
