### PR TITLE
@dakacki welcome file

### PR DESCRIPTION
**Pull request by DAkacki**
## Who dat? - 
Danny Akacki

## What dat? - 
Intrusion Detection Analyst

## Where dat? - 
GE Capital

### CODE REVIEW

**Comment by jaelle** [comment]
It's a start! Maybe add more details? :smile:

**Comment by DAkacki** [comment]
@jaelle better?

**Comment by jaelle** [comment]
Did anything change?

**Comment by DAkacki** [comment]
@jaelle do you see my changes now?

**Comment by jaelle** [comment]
@DAkacki Looks great! :shipit:

**Pull request merged**
