### PR TITLE
Create kimonotocat.md

### PR DESCRIPTION
**Pull request by katiepatch**
Kimonotocat's greeting to the world.

### CODE REVIEW

**Comment by siakaramalegos** [comment]
love the kimono octokitty

**Comment by crichID** [comment]
:+1: Did you find her in the stickers we brought?

**Comment by siakaramalegos** [comment]
@crichID sadly, no :(

**Comment by katiepatch** [comment]
@crichID I wish, I just found her at https://octodex.github.com/

**Comment by efenske** [comment]
Looks great!

**Pull request merged**
