### PR TITLE
@GitHubteacher welcome file

### PR DESCRIPTION
**Pull request by githubteacher**
This feature adds the GitHub Teacher file into the `personal-files` folder

This adds `github-sample-teacher.md` which describes more about me!

:+1: :tada: :smile_cat:

### CODE REVIEW

**Comment by githubteacher** [comment]
hey @bhuga, can i :shipit: :ship: :boat:

**Comment by bhuga** [comment]
:sweat_smile: :+1: :grin:

**Comment by DAkacki** [comment]
# Needs more emoji

**Comment by MsGrayson** [comment]
:hamster: :heart:

**Comment by githubteacher** [comment]
@DAkacki i added a :house: icon. Is this good?

**Comment by DAkacki** [comment]
@githubteacher roger dat.

**Pull request merged**
